---
#
# Oracle Database as a Service 
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to gather Oracle resources on Oracle Exadata Database Service, BaseDB and on-prem. 
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

- name: assert oracle_meta_assert_password
  when:
    - oracle_meta_assert_password | default(true)
  tags:
    - always
    - oracle_assert 
  block:

    - name: Assert password
      ansible.builtin.assert:
        that: 
          - "{{ assert_password }} | length >= 8"
          - "{{ assert_password }} | length <= 30"
          - "{{ assert_password }} | regex_search('[0-9]')"
          - "{{ assert_password }} | regex_search('[a-z]')"
          - "{{ assert_password }} | regex_search('[A-Z]')"
          - "{{ assert_password }} | select('search', regex)"
      vars:
        PATTERNS:
          - '\-'
          - '\!'
          - '\@'
          - '\%'
          - '\&'
          - '\*'
          - '\.'
          - '\#'
          - '\_'
        regex: "{{ PATTERNS | join('|') }}"

  rescue:

    - name: Assert password failed 
      debug:
        msg: >-
          Password length should be between 8 and 30 characters, and should contain at least: 
            * One lowercase [a..z] character
            * One uppercase [A..Z] character
            * One digit [0..9]
            * One special character [- ! @ % & * . # _] 

    # default is => Fail execution of Playbook
    - name: Fail execution of oracle_meta
      ansible.builtin.fail:
        msg: >-
          Set oracle_meta_assert_password=false in inventory/group_vars/all to disable this fail task.
      when:
        - oracle_meta_assert_password | default(true)

...