---
changelog_filename_template: ../CHANGELOG.rst
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
prelude_section_name: release_summary
prelude_section_title: Release Summary
flatmap: true
sections:
  - - major_changes
    - Major Changes
  - - minor_changes
    - Minor Changes
    - 20250225_gghub_goldengate_deploy - openssl self signed cert runnin on one node only
    - 20250225_gghub_software_deploy - create goldengate environment file
    - 20250225_gghub_remove - deinstall xag
    - 20250225_gghub_deploy.yml - gg_deployment_password confirmation
  - - breaking_changes
    - Breaking Changes / Porting Guide
  - - deprecated_features
    - Deprecated Features
  - - removed_features
    - Removed Features (previously deprecated)
  - - security_fixes
    - Security Fixes
  - - bugfixes
    - Bugfixes
  - - known_issues
    - Known Issues
  - - doc_changes
    - Documentation Changes
title: "Oracle Dbaas Collection"
trivial_section_name: trivial
