---
#
# Oracle Database as a Service 
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to gather Oracle resources on Oracle Exadata Database Service, BaseDB and on-prem. 
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

- name: DBaasCA - Gather database facts 
  ansible.builtin.include_tasks: dbaasca/getDetails.yml
  when: 
    - oracle_facts.system.crs_on | default(false)
    - not oracle_facts.system.dbaascli

- name: DBaasCLI - Gather database facts 
  ansible.builtin.include_tasks: dbaascli/getDetails.yml
  when: 
    - oracle_facts.system.dbaascli

- name: LVM - Gather database facts 
  ansible.builtin.include_tasks: lvm/getDetails.yml
  when: 
    - not oracle_facts.system.crs_on | default(false)
    - not oracle_facts.system.dbaascli

- name: Database Target Block 
  when: database_config.db_role is not defined
  block:

  - name: Set remaining hosts as not missing
    ansible.builtin.set_fact:
      dbtarget_success: true

  - name: Save job_report facts under Ansible controller
    delegate_to: localhost
    delegate_facts: true
    set_fact:
      dbtarget_list: '{{ hostvars | dict2items | json_query(dbtarget_query) }}'
    vars:
      dbtarget_query: "[?value.dbtarget_success==`true`].key"

  - name: Set target fact
    ansible.builtin.set_fact:
      targetHome: true
      hostname_target: "{{ hostvars['localhost']['dbtarget_list'] | sort | first }}"

...